services:
  db:
      image: mysql
      container_name: db
      volumes:
        - mysql-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_ROOT_USER=root
        - MYSQL_DATABASE=todo
      ports:
        - 3306:3306
  app:
    build:
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3050:3050
      - 5050:5050
    restart: always
    depends_on:
      - db


volumes:
  mysql-data: ~  
  



